import { CalendarDays, MapPin, Ticket as TicketIcon } from "lucide-react";
import { formatDateTime } from "@/lib/utils";
import type { TicketDesign } from "@/lib/types";

export interface TicketPreviewData {
  eventTitle: string;
  ticketTypeName: string;
  venue?: string | null;
  city?: string | null;
  country?: string | null;
  startsAt?: string | null;
  holderName?: string | null;
  reference?: string | null;
  price?: number | null;
  currency?: string;
  qrDataUrl?: string | null; // rendered QR png; if absent shows placeholder
  design?: TicketDesign;
  organizer?: string | null;
}

const DEFAULTS: Required<Pick<TicketDesign, "primaryColor" | "accentColor" | "bgColor" | "textColor">> = {
  primaryColor: "#7C3AED",
  accentColor: "#EC4899",
  bgColor: "#0B0A1A",
  textColor: "#FFFFFF",
};

/**
 * Visual representation of an Eventiko ticket. Used both in the seller
 * customization studio (live preview) and on the buyer's confirmation page.
 * The PDF generated by the backend mirrors this layout.
 */
export function TicketPreview({ data }: { data: TicketPreviewData }) {
  const d = { ...DEFAULTS, ...(data.design || {}) };
  const showQr = data.design?.showQr !== false;
  const perks = data.design?.perks?.filter(Boolean) ?? [];

  return (
    <div
      className="relative mx-auto w-full max-w-md overflow-hidden rounded-3xl shadow-2xl"
      style={{ background: d.bgColor, color: d.textColor }}
    >
      {/* Top banner */}
      <div
        className="relative px-6 pt-6 pb-5"
        style={{
          backgroundImage: `linear-gradient(135deg, ${d.primaryColor} 0%, ${d.accentColor} 100%)`,
        }}
      >
        {data.design?.bannerUrl && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={data.design.bannerUrl}
            alt=""
            className="absolute inset-0 h-full w-full object-cover opacity-30"
          />
        )}
        <div className="relative flex items-start justify-between gap-3">
          <div className="flex items-center gap-2">
            {data.design?.logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={data.design.logoUrl} alt="" className="h-9 w-9 rounded-lg object-cover" />
            ) : (
              <span className="grid h-9 w-9 place-items-center rounded-lg bg-white/20">
                <TicketIcon className="h-5 w-5 text-white" />
              </span>
            )}
            <span className="text-xs font-semibold uppercase tracking-widest text-white/90">
              {data.organizer || "Eventiko"}
            </span>
          </div>
          <span className="rounded-full bg-white/20 px-3 py-1 text-xs font-bold text-white">
            {data.ticketTypeName}
          </span>
        </div>
        <h3 className="relative mt-4 font-display text-2xl font-extrabold leading-tight text-white">
          {data.eventTitle}
        </h3>
      </div>

      {/* Perforation */}
      <div className="relative h-0">
        <div className="absolute -left-3 top-1/2 h-6 w-6 -translate-y-1/2 rounded-full" style={{ background: "#f8fafc" }} />
        <div className="absolute -right-3 top-1/2 h-6 w-6 -translate-y-1/2 rounded-full" style={{ background: "#f8fafc" }} />
        <div className="mx-6 border-t border-dashed border-white/25" />
      </div>

      {/* Body */}
      <div className="px-6 py-5">
        <div className="grid grid-cols-2 gap-4 text-sm">
          <Detail icon={<CalendarDays className="h-4 w-4" />} label="Date & time" value={data.startsAt ? formatDateTime(data.startsAt) : "TBA"} accent={d.accentColor} />
          <Detail icon={<MapPin className="h-4 w-4" />} label="Venue" value={[data.venue, data.city].filter(Boolean).join(", ") || "TBA"} accent={d.accentColor} />
          <Detail label="Holder" value={data.holderName || "Bearer"} accent={d.accentColor} />
          <Detail label="Reference" value={data.reference || "EVK-XXXX-XXXX"} accent={d.accentColor} mono />
        </div>

        {perks.length > 0 && (
          <div className="mt-4 flex flex-wrap gap-1.5">
            {perks.map((p) => (
              <span
                key={p}
                className="rounded-full px-2.5 py-0.5 text-[11px] font-semibold"
                style={{ background: `${d.accentColor}22`, color: d.accentColor }}
              >
                {p}
              </span>
            ))}
          </div>
        )}

        {/* QR */}
        {showQr && (
          <div className="mt-5 flex items-center gap-4 rounded-2xl bg-white p-4">
            <div className="grid h-28 w-28 shrink-0 place-items-center overflow-hidden rounded-xl bg-white ring-1 ring-slate-200">
              {data.qrDataUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={data.qrDataUrl} alt="Ticket QR code" className="h-full w-full object-contain" />
              ) : (
                <QrPlaceholder />
              )}
            </div>
            <div className="text-slate-700">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Scan at the door</p>
              <p className="mt-1 text-sm font-medium leading-snug">
                Present this QR code on your phone. Keep the reference number as a backup.
              </p>
            </div>
          </div>
        )}

        {data.design?.terms && (
          <p className="mt-4 text-[11px] leading-relaxed opacity-70">{data.design.terms}</p>
        )}
      </div>

      {/* Footer strip */}
      <div className="flex items-center justify-between px-6 pb-5 pt-1 text-[11px] opacity-70">
        <span>Powered by Eventiko</span>
        <span className="font-semibold">eventiko.com</span>
      </div>
    </div>
  );
}

function Detail({
  icon,
  label,
  value,
  accent,
  mono,
}: {
  icon?: React.ReactNode;
  label: string;
  value: string;
  accent: string;
  mono?: boolean;
}) {
  return (
    <div>
      <div className="flex items-center gap-1 text-[11px] font-semibold uppercase tracking-wide opacity-60" style={{ color: accent }}>
        {icon}
        {label}
      </div>
      <div className={`mt-0.5 ${mono ? "font-mono text-sm" : "text-sm font-semibold"}`}>{value}</div>
    </div>
  );
}

function QrPlaceholder() {
  return (
    <svg viewBox="0 0 100 100" className="h-20 w-20 text-slate-900">
      <rect x="0" y="0" width="30" height="30" fill="currentColor" />
      <rect x="8" y="8" width="14" height="14" fill="#fff" />
      <rect x="70" y="0" width="30" height="30" fill="currentColor" />
      <rect x="78" y="8" width="14" height="14" fill="#fff" />
      <rect x="0" y="70" width="30" height="30" fill="currentColor" />
      <rect x="8" y="78" width="14" height="14" fill="#fff" />
      <rect x="40" y="0" width="8" height="8" fill="currentColor" />
      <rect x="52" y="12" width="8" height="8" fill="currentColor" />
      <rect x="40" y="40" width="20" height="20" fill="currentColor" />
      <rect x="70" y="50" width="8" height="8" fill="currentColor" />
      <rect x="85" y="65" width="8" height="8" fill="currentColor" />
      <rect x="50" y="80" width="8" height="8" fill="currentColor" />
      <rect x="70" y="85" width="12" height="12" fill="currentColor" />
    </svg>
  );
}
